# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-29 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190830_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='apt',
        ),
        migrations.AddField(
            model_name='order',
            name='box_theme',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
