# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-01 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191029_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hash_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
